- name: Download script
  ansible.builtin.get_url:
    url: "{{ bareos_install_script }}"
    dest: /tmp/bareos-install.sh

- name: Make script executable
  ansible.builtin.file:
    path: /tmp/bareos-install.sh
    mode: '0744'

- name: Remove gpg key
  ansible.builtin.file:
    path: /etc/apt/keyrings/bareos-experimental.gpg
    state: absent

- name: Add bareos repo
  ansible.builtin.shell:
    cmd: /tmp/bareos-install.sh
